steps:
  # 1. Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    # Define o diretório de trabalho para o passo de build
    dir: 'lgpd-backend-apis'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sistemalgpd:latest', '.']

  # 2. Envia a imagem para o Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sistemalgpd:latest']

images:
  - 'gcr.io/$PROJECT_ID/sistemalgpd:latest'