# cloudbuild.yaml
# CI/CD para o back-end LGPD (Cloud Run + GitHub)
# Este arquivo orquestra o build, teste e deploy de todos os microsserviços.

steps:
# Passo 1: Instalar dependências e executar testes unitários
- name: 'gcr.io/cloud-builders/npm'
  id: Testes Unitários
  dir: 'lgpd-backend-apis' # Executa os comandos dentro da pasta do backend
  entrypoint: 'bash'
  args: ['-c', 'npm install && npm test']

# Passo 2: Construir a imagem do contêiner
# Usa o Dockerfile para criar a imagem base que será usada por todos os microsserviços
- name: 'gcr.io/cloud-builders/docker'
  id: Build Imagem
  dir: 'lgpd-backend-apis' # O build do docker deve ocorrer onde o Dockerfile está
  args:
  - 'build'
  - '-t'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/lgpd-backend-apis:$COMMIT_SHA' # NOVO CAMINHO
  - '.'

# Passo 3: Enviar a imagem para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Imagem
  args:
  - 'push'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/lgpd-backend-apis:$COMMIT_SHA' # NOVO CAMINHO

# Passo 4: Deploy do Monolito Modular (server.js)
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Monolito LGPD
  args:
  - 'run'
  - 'deploy'
  - 'lgpd-api-gateway' # Nome do serviço no Cloud Run
  - '--image'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/lgpd-backend-apis:$COMMIT_SHA' # NOVO CAMINHO
  - '--region'
  - 'us-central1' # Região do seu serviço Cloud Run
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Permite acesso público, remova se for um serviço interno

# ##################################################################
# VARIÁVEIS DE SUBSTITUIÇÃO (Definidas no Gatilho do Cloud Build)
# ##################################################################
substitutions:
  _AR_REPO_NAME: 'lgpd-backend-repo' # Nome do repositório que você criou
  _AR_REGION: 'us-central1' # Região do repositório