# cloudbuild.yaml
# CI/CD para o back-end LGPD (Cloud Run + GitHub)
# Este arquivo orquestra o build, teste e deploy de todos os microsserviços.

steps:
# Passo 1: Instalar dependências e executar testes unitários
- name: 'gcr.io/cloud-builders/npm'
  id: Testes Unitários
  entrypoint: 'bash'
  args: ['-c', 'npm install && npm test']

# Passo 2: Construir a imagem do contêiner
# Usa o Dockerfile para criar a imagem base que será usada por todos os microsserviços
- name: 'gcr.io/cloud-builders/docker'
  id: Build Imagem
  args:
  - 'build'
  - '-t'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/lgpd-backend-apis:$COMMIT_SHA' # NOVO CAMINHO
  - '.'

# Passo 3: Enviar a imagem para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Imagem
  args:
  - 'push'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/lgpd-backend-apis:$COMMIT_SHA' # NOVO CAMINHO

# ##################################################################
# PASSOS DE DEPLOY PARA O MONOLITO MODULAR (Cloud Run)
# ##################################################################

# Passo 4: Deploy do Monolito Modular (server.js)
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Monolito LGPD
  entrypoint: 'bash'
  # cloudbuild.yaml (Trecho - Passo 4: Deploy Monolito LGPD)
  # ...
  args:
  - 'run'
  - 'deploy'
  - 'lgpd-api-gateway'
  - '--image'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/lgpd-backend-apis:$COMMIT_SHA' # NOVO CAMINHO
  # ...

# ##################################################################
# VARIÁVEIS DE SUBSTITUIÇÃO (Definidas no Gatilho do Cloud Build)
# ##################################################################
substitutions:
  _DB_USER: 'root' # Usuário do Cloud SQL
  # _DB_PASSWORD foi removido e será gerenciado pelo Secret Manager
  _DB_NAME: 'lgpd_db' # Nome do Banco de Dados
  _INSTANCE_CONNECTION_NAME: 'project-1685bd27-89e0-4455-bda:us-central1:lgpd-db-instance' # Conexão do Cloud SQL
  _API_AUDITORIA_URL: 'https://api-auditoria-xxxxxxxx-uc.a.run.app' # URL da API de Auditoria (DEVE SER ATUALIZADA APÓS O PRIMEIRO DEPLOY)
  # ... (outras variáveis) ...
  _AR_REPO_NAME: 'lgpd-backend-repo' # Nome do repositório que você criou
  _AR_REGION: 'us-central1' # Região do repositório