# cloudbuild.yaml
# CI/CD para o back-end LGPD (Cloud Run + GitHub)
# Este arquivo orquestra o build, teste e deploy de todos os microsserviços.

steps:
# Passo 1: Instalar dependências e executar testes unitários
- name: 'gcr.io/cloud-builders/npm'
  id: Testes Unitários
  entrypoint: 'bash'
  args: ['-c', 'npm install && npm test']

# Passo 2: Construir a imagem do contêiner
# Usa o Dockerfile para criar a imagem base que será usada por todos os microsserviços
- name: 'gcr.io/cloud-builders/docker'
  id: Build Imagem
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/lgpd-backend-apis:$COMMIT_SHA'
  - '.'

# Passo 3: Enviar a imagem para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Imagem
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/lgpd-backend-apis:$COMMIT_SHA'

# ##################################################################
# PASSOS DE DEPLOY PARA O MONOLITO MODULAR (Cloud Run)
# ##################################################################

# Passo 4: Deploy do Monolito Modular (server.js)
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Monolito LGPD
  args:
  - 'run'
  - 'deploy'
  - 'lgpd-api-gateway' # Novo nome do serviço
  - '--image'
  - 'gcr.io/$PROJECT_ID/lgpd-backend-apis:$COMMIT_SHA'
  - '--region'
  - 'us-central1' # SUBSTITUA PELA SUA REGIÃO
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Ajuste conforme sua necessidade de autenticação
  - '--set-env-vars'
  - 'DB_USER=$$DB_USER,DB_PASSWORD=$$DB_PASSWORD,DB_NAME=$$DB_NAME,INSTANCE_CONNECTION_NAME=$$INSTANCE_CONNECTION_NAME'
  - '--set-cloudsql-instances'
  - '$$INSTANCE_CONNECTION_NAME'
  - '--command'
  - 'npm'
  - '--args'
  - 'start' # Usa o script 'start' do package.json
  env:
  - 'DB_USER=${_DB_USER}'
  - 'DB_PASSWORD=${_DB_PASSWORD}'
  - 'DB_NAME=${_DB_NAME}'
  - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'

# ##################################################################
# VARIÁVEIS DE SUBSTITUIÇÃO (Definidas no Gatilho do Cloud Build)
# ##################################################################
substitutions:
  _DB_USER: 'root' # Usuário do Cloud SQL
  _DB_PASSWORD: 'your-db-password' # Senha do Cloud SQL
  _DB_NAME: 'lgpd_db' # Nome do Banco de Dados
  _INSTANCE_CONNECTION_NAME: 'project-id:region:instance-name' # Conexão do Cloud SQL
  _API_AUDITORIA_URL: 'https://api-auditoria-xxxxxxxx-uc.a.run.app' # URL da API de Auditoria (DEVE SER ATUALIZADA APÓS O PRIMEIRO DEPLOY)
